### ISSUE TITLE
Do not map F7,F8 etc. by default

### ISSUE THREAD

**Issue by sergei-dyshel** [rickhowe/diffchar.vim#1]
Or at least add an option to disable these mappings!
Thanks!

**Comment by rickhowe** [comment]
Thanks for asing. How about disabling those key mapping like this in your vimrc?
`map <silent> <Nop> <Plug>ToggleDiffCharAllLines`
`map <silent> <Nop> <Plug>ToggleDiffCharCurrentLine`

**Comment by rickhowe** [comment]
How about disabling those key mappings like this in you vimrc?
`map <silent> <Nop> <Plug>ToggleDiffCharAllLines`
`map <silent> <Nop> <Plug>ToggleDiffCharCurrentLine`

**Comment by rickhowe** [comment]
How about setting non-existent virtual keys in your vimrc to disable those mappings like this?
```
map <F19> <Plug>ToggleDiffCharAllLines
map <F20> <Plug>ToggleDiffCharCurrentLine
```

**Comment by sergei-dyshel** [comment]
That's what I'm doing now. But IMHO user should be able to disable these mappings altogether  with just one line of code. 
Another option is to map only the keys which aren't mapped yet.

**Comment by john-kurkowski** [comment]
Since this issue opened, this plugin has overwritten a couple more of my mappings: `<Leader>g` and `<Leader>p`. It is cumbersome to have to track down why my mapping stopped working. Then return to this GitHub issue. Then piecemeal blacklist this plugin's new mappings. Then maintain that blacklist. I think the plugin should be polite by default, as the previous comment suggested.

**Comment by rickhowe** [comment]
Thank you. I just updated to 7.2 not to map the keys which have been used. Please check.

**Comment by john-kurkowski** [comment]
Works great! Thank you!
