### ISSUE TITLE
Doesn't work for Vim 7

### ISSUE THREAD

**Issue by bam80** [rickhowe/diffchar.vim#18]
Thanks for plugin.
Just curios why it needs vim 8?

And it should be mentioned in Readme

**Comment by rickhowe** [comment]
Thanks for using.
There are several useful features in 8.0 and
It became not easy to maintain different codes for 7,x and 8.0 both.
And 2 years has passed since 8.0 release. I decided to support only 8.0.
I mentioned it in Reamde as a change history on diffchar 8.0.

Which 7.x version and which patch number you want to use?
Depending on it, the latest diffchar 8.4 might work.

**Comment by bam80** [comment]
Thanks. Can't use it still)
Didn't see the mention in Readme, sorry.
I use Vim 7.4.1938

**Comment by rickhowe** [comment]
Could you try to edit plugin/diffchar.vim on your PC?
line 16:
`if exists('g:loaded_diffchar') || !has('diff') || v:version < 800`
to
`if exists('g:loaded_diffchar') || !has('diff') || v:version < 740 || !has('patch-7.4.1895')`

If you have 7.4.1895 or more, it might work. Otherwise, please continue to use diffchar 7.6.

**Comment by bam80** [comment]
I will, thanks.
If it work, does it mean it will work for all cases for my vim version, or it might work is some cases and not in others?

**Comment by rickhowe** [comment]
Sorry, you need 7.4.2204 or later with the latest diffchar 8.4.

`if exists('g:loaded_diffchar') || !has('diff') || v:version < 704 || !has('patch-7.4.2204')`

If you can not update your vim, please use 7.6

**Comment by bam80** [comment]
I'll try to upgrade from Slackware-current, thanks!

**Comment by bam80** [comment]
At last I upgraded it, and.. it works!
Thanks you a lot! )

![image](https://user-images.githubusercontent.com/233979/53978724-feb9f400-411c-11e9-83df-2d6e2661d4e9.png)

**Comment by bam80** [comment]
By the way, I'm looking for a good color scheme.
If you know better than on the screenshot, please, let me know!
Thanks

**Comment by rickhowe** [comment]
That is not a recommendation but I always use 'delek' with white background. And sometimes use t:DiffColors option to distinguish a diff unit in a line.

**Comment by bam80** [comment]
Hmm, it's hard to catch from the animated GIF what the t:DiffColors option does..
Maybe add static screenshots for every option?

**Comment by rickhowe** [comment]
Here they are. Hope this helps.

![00](https://user-images.githubusercontent.com/3096934/54084192-0b368a80-4371-11e9-8d4a-2610826a99b7.gif)


![33](https://user-images.githubusercontent.com/3096934/54084200-23a6a500-4371-11e9-8a70-528f7886be56.gif)

**Comment by bam80** [comment]
Thanks. I think it would be fine to add it to the Readme.

**Comment by rickhowe** [comment]
Readme already mentioned t:DiffColors and other options.

**Comment by bam80** [comment]
@rickhowe I meant the screenshots.
